Tune town should only play when enabled
animal-crossing-music-extension/ac-music-extension pull request #139
Opened 2020-06-09 19:12 UTC by paladique

Fixes #131 

Logic in the `StateManager.js` only checked the `absoluteTownTune` setting, so the hourly tune/town tune would continue to play even when `enableTownTune` is false. 

Decided to keep this change small and check the `enableTownTune` setting as well. Optionally, `absoluteTownTune` could be set to false/unchecked as well, but decided against altering user settings.

2020-06-09 19:40 UTC, paladique commented
@ilikecorndogs any thoughts on preserving the "play while paused" setting and keeping it checked, even when town tune is unchecked?

2020-08-31 11:30 UTC, ilikecorndogs requested changes
fixes bug on opera gx, however, it appears to not play custom tunes while the music is paused, despite the options being selected correctly (both being checked). while music is unpaused with these settings, it plays. perhaps it is due to a lack of audio permissions to play audio?  https://imgur.com/a/ONFYzrH options used in linked picture

2020-10-05 11:46 UTC, PikaDude commented
> fixes bug on opera gx, however, it appears to not play custom tunes while the music is paused, despite the options being selected correctly (both being checked). while music is unpaused with these settings, it plays. perhaps it is due to a lack of audio permissions to play audio? https://imgur.com/a/ONFYzrH options used in linked picture

I can't seem to reproduce this, even on Opera GX.

2020-10-05 11:46 UTC, PikaDude approved these changes

2020-10-14 20:46 UTC, merged